### ISSUE TITLE
Not working with videojs v5.2.4 (latest release)

### ISSUE THREAD

**Issue by Viper177** [funnyordie/videojs-relatedCarousel#2]
Hi
I am currently working with version 5.2.4 and your plugin is giving me errors:

Cannot read property 'extend' of undefined 
at line 57
 var RelatedCarouselButton = vjs.Button.extend({

But when i change you code:
var RelatedCarouselButton = vjs.Button.extend({
      init: function(player, options) {
        vjs.Button.call(this, player, options);
      }
    });

into this:

var Button = vjs.getComponent("Button");
      var RelatedCarouselButton = vjs.extend(Button,{
      init: function(player, options) {
        vjs.call(this, player, options);
      }
    });

I have changed the method to extend Button component and how to call it here according to v5.2.4.

It work but again show error at next point:
Uncaught TypeError: The element or ID supplied is not valid. (videojs)

I am not aware how to deal with it.

 Can you please mention the version of videojs your plugin supports? It will be helpful in implementing this feature.

**Comment by codex-corp** [comment]
Here an update for support videojs 5 
https://github.com/alex-phillips/videojs-relatedCarousel/tree/videojs-5-support

**Comment by jgubman** [comment]
should be fixed in 
https://github.com/funnyordie/videojs-relatedCarousel/commit/84722b49eb74561533a059bbe77e75d61f83d69c
